### ISSUE TITLE
convert to principal charm

### ISSUE THREAD

**Issue by gmeszaros** [ChrisMacNaughton/charm-sysctl#1]
Hello Chris,

I was wondering if it would make sense to move this charm to be a principal charm, instead of requiring another charm to be its subordinate one.
Rationale: I have a couple of nodes deployed by maas as bare metals and only hosting containers. I could put an ubuntu charm on top of it, but it's just not as clean as if it had this charm only.

Thanks,
Gabor

**Comment by ChrisMacNaughton** [comment]
Done!
